[package]
name = "rust_leveldb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leveldb = "0.8.6"
serde = "1.0.193"
serde_json = "1.0.108"
string = "0.3.0"
tempdir = "0.3.7"

